### ISSUE TITLE
World-space position estimation

### ISSUE THREAD

**Issue by apkd** [keijiro/FaceMeshBarracuda#1]
Thanks for sharing this project, these samples are super valuable. Amazing stuff!

I have managed to run FaceMeshBarracuda locally without issue. However, I noticed that the face mesh is essentially a 2D projection distorted/scaled to fit the webcam image. What I hoped to accomplish was to estimate the actual world-space position/rotation of the face (even if the unit scale wouldn't be accurate). I don't actually need the mesh, just tracking of the approximate head transform.

I am assuming that won't be possible to estimate using this package. Given that you've been porting a lot of similar packages to Barracuda recently, do you know of any other Barracuda-compatible models I could experiment with?

**Comment by keijiro** [comment]
Please check the original MediaPipe documentation. You have to implement missing pieces like the Procrustes analyzer, the 3D metric reprojector, etc.

https://google.github.io/mediapipe/solutions/face_mesh.html

**Comment by keijiro** [comment]
I'm closing this issue now as I answered the question in the original post. Please create a new issue for other problems.

**Comment by keijiro** [comment]
(In other words, there is no further machine-learning magic. You have to deal with math problems to get what you want.)

**Comment by apkd** [comment]
Many thanks!
