### ISSUE TITLE
Support for Blendshapes

### ISSUE THREAD

**Issue by danielpfbs** [keijiro/FaceMeshBarracuda#10]
Thanks for the awesome project. I was interested in trying to translate this to work with facial blend shapes on a 3D characters. Any examples or ideas for how to do that?

**Comment by keijiro** [comment]
The short answer is no. I have never tried facial blendshape animation. So, unfortunately, I have no idea about it.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by jawa64** [comment]
@danielpfbs if i gather what you are asking correctly and happen to have an arkit compatible phone that already exists for unity https://apps.apple.com/app/id1544159771 another posthoc option would be puppetface.
