### ISSUE TITLE
The mesh is not rendered

### ISSUE THREAD

**Issue by marcin-dzieszko** [keijiro/FaceMeshBarracuda#11]
Hi,

**thank you for this project :-)**

I'm new to Unity ...

I had a problem ... the camera view is shown (_Main object_ ) but only this one ... no other objects (_Face, Left Eye & Right Eye_) are rendered ... also the meshes are not rendered at all ... so only the camera view is visible ...

the method Visualizer::OnRenderObject is called and the calculations there looks fine (I debugged them) ... so not sure what is the problem ....

Im using 2021.1.3f1 ...

Could you please give some tips what should I check?

Thanks in advance,
Best Regards,
MD

**Comment by keijiro** [comment]
- Which platform are you using? (Mac or Windows?)
- OS version
- GPU

**Comment by marcin-dzieszko** [comment]
Windows 10 Pro x64
OS compilation: 19042.1586
GPU: Intel UHD Graphics 620

**Comment by keijiro** [comment]
Intel UHD Graphics 620 sounds like a bit too old, but it should still work.

How about other simpler Barracuda samples? Like MNIST? https://github.com/keijiro/MnistBarracudaGpu

**Comment by marcin-dzieszko** [comment]
I launched this project and I can see the following:

![image](https://user-images.githubusercontent.com/95860722/160553914-327f03d4-ab8a-4bc6-ae76-0ae2da92cd2b.png)

**Comment by marcin-dzieszko** [comment]
Is it fine?

**Comment by keijiro** [comment]
Yes, fine. It looks working correctly.

How about more complex sample? Like BlazeFace? https://github.com/keijiro/BlazeFaceBarracuda

**Comment by marcin-dzieszko** [comment]
Looks this one did not recognize the faces ... so maybe this is indeed my GPU issue ... what do you think?

Im looking for desktop with better GPU ...

![image](https://user-images.githubusercontent.com/95860722/160568610-4070e8e5-1526-4c9e-bbbd-939a59021093.png)

**Comment by keijiro** [comment]
BlazeFace is relatively light neural network model, so it should run on every GPU.

I guess there is something wrong with your GPU. I'd recommend updating the graphics driver if available.

**Comment by marcin-dzieszko** [comment]
Looks I have the leatest one.
Thank you for your support - I will try to launch it on PC with better GPU ... and let you know what will be the result

**Comment by marcin-dzieszko** [comment]
I will borrow cp with nvidia k4000 - I think this should be good enough :-)

**Comment by marcin-dzieszko** [comment]
After using  nvidia k4000 it started working fine,
thank you for your help 👍

**Comment by keijiro** [comment]
Although I think it could run even on integrated Intel GPUs, upgrading your GPU is the most straightforward solution for the problem.

**Comment by marcin-dzieszko** [comment]
I checked - I have the newest drivers on my GPU - at this moment I don't know what I could do to make run on the GPU ...
