### ISSUE TITLE
eyeiris didn't work

### ISSUE THREAD

**Issue by KARAMKIM88** [keijiro/FaceMeshBarracuda#12]
![스크린샷, 2022-04-19 12-49-47](https://user-images.githubusercontent.com/8295381/163921190-43c91057-beca-489c-baff-b8d84015edb5.png)

I thought  _pipeline.RawLeftEyeVertexBuffer has 67 vertices.
but only 5 points have 3d locations.
Do i miss something?
thanks for your answer.

**Comment by keijiro** [comment]
Could you try IrisBarracuda? Does it work on you environment?

https://github.com/keijiro/IrisBarracuda

**Comment by KARAMKIM88** [comment]
> Could you try IrisBarracuda? Does it work on you environment?
> 
> https://github.com/keijiro/IrisBarracuda
![스크린샷, 2022-04-19 14-26-52](https://user-images.githubusercontent.com/8295381/163926261-0f1b7120-337b-4ef6-a9e8-9a97d649aa03.png)

I also tested irisbarracuda
my environment is Ubuntu..
Does it make problem?
Thanks for quick answer
I really appreciated it

**Comment by keijiro** [comment]
It seems that you're using OpenGL. Could you try changing it to Vulkan?

**Comment by KARAMKIM88** [comment]
omg..
it works
I really thank you....
if you didn't help me, i couldn't solve the problem...
![스크린샷, 2022-04-19 15-14-50](https://user-images.githubusercontent.com/8295381/163938085-5c6d621f-6db1-455b-9082-03d5e23e8882.png)

I can't say how much i thank you

**Comment by keijiro** [comment]
Thanks for the clarification. I'll recommend Linux users to use Vulkan from now on.
