### ISSUE TITLE
RefinedFaceMesh results were often broken

### ISSUE THREAD

**Issue by KARAMKIM88** [keijiro/FaceMeshBarracuda#13]
Hi
often RefinedFaceMesh were broken
after rebooting the unity editor, it worked fine.
but I don't know the reason
Thanks for helping me

![스크린샷, 2022-04-26 15-03-47](https://user-images.githubusercontent.com/8295381/165232811-9e4cb7e5-87c7-4b34-a1fe-f5490d049397.png)

**Comment by keijiro** [comment]
How about other Barracuda samples? You can find bunch of them in my repositories.

https://github.com/keijiro?tab=repositories&q=barracuda

**Comment by keijiro** [comment]
I close this issue due to inactivity.
