### ISSUE TITLE
Recognizing face that is upside down

### ISSUE THREAD

**Issue by marcin-dzieszko** [keijiro/FaceMeshBarracuda#14]
Hello,

We noticed the algorithm with face recognition works when the face is tilted not more than ~45 degrees. When the angle is more significant it stops working

Would it be possible whether the algorithm works with a face that is upside down?
If so what changes would be required?

Thanks in advance,
MD

**Comment by keijiro** [comment]
This is not an "algorithm". It's machine learning.

You can detect flipped faces if you train the model with flipped face images.
