### ISSUE TITLE
How to render the face mesh

### ISSUE THREAD

**Issue by MolianWH** [keijiro/FaceMeshBarracuda#15]
Thanks for your great work.
I want to make a face texture for the face mesh. I set the `this.GetComponent<MeshFilter>().mesh = _resources.faceMeshTemplate;` in Visualizer.cs `OnPostRender()` function. but it not work. By the way, I found the ` _resources.faceMeshTemplate.Vertices` are all zero. So which mesh can set UVs and be shown?
I am not very familiar with unity and CG.  The above statement may be not very accurate. Could you please provide some ideas for that task? Thanks!

example about what I want to implement
![image](https://user-images.githubusercontent.com/33748947/173172876-9966cc7d-6892-4fcf-bd4c-e5a59989bd1a.png)

**Comment by keijiro** [comment]
> I found the _resources.faceMeshTemplate.Vertices are all zero

Because it only contains index data. Vertices are given externally.

I'd recommend reading `Visualizer.cs` and `Visualizer.shader` in the FaceLandmarkBarracuda project. 

https://github.com/keijiro/FaceLandmarkBarracuda

**Comment by keijiro** [comment]
Or use this branch. I'm not sure if it still runs (may be broken due to compatibility issues).

https://github.com/keijiro/FaceMeshBarracuda/tree/landmark-detector

**Comment by MolianWH** [comment]
Thanks. I will try it.
