### ISSUE TITLE
Is it possible to use 16:9 ratio of webcam input

### ISSUE THREAD

**Issue by tszyeung** [keijiro/FaceMeshBarracuda#16]
I've tried to change the input webcam resolution to 1920x1080, but the mesh position is incorrect and it is seems only crop the center part for the face detection processing. Also, the detection is not as smooth as the sample.

**Comment by keijiro** [comment]
The MediaPipe models are implemented for 1:1 rectangular image inputs, so you only can use 1:1 images.
