### ISSUE TITLE
Question: Performance on Android ~13 fps vs ~30fps on Unity Editor, how to optimize performance

### ISSUE THREAD

**Issue by victorcfk** [keijiro/FaceMeshBarracuda#17]
Hi @keijiro, thank you for the great project. I've run the project on Android and I'm getting much lower FPS vs Unity Editor. Could I ask for any advice to tune the performance for Android? This project uses computeshader and much of the advice for optimizing Barracuda is for creating and running tensors.

I've tested the[ Google mediapipe demo](https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html?model=mediapipe_face_mesh) and the performance is closer to that of unity editor demo, so it seems like its possible to reach that level optimization on the same mobile hardware.

**Comment by keijiro** [comment]
> I've tested the[ Google mediapipe demo](https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html?model=mediapipe_face_mesh)

Did you test it on the mobile device?

**Comment by vikvic** [comment]
Hi Keijiro, yes I just did on a Samsung S22. I'm getting 40 fps in the mobile browser.

**Comment by victorcfk** [comment]
Hi Keijiro, yes I just did on a Samsung S22. I'm getting 40 fps in the mobile browser. Used my other account, apologies for the confusion

**Comment by keijiro** [comment]
Did you try Vulkan? (Player Settings -> Graphics API)

**Comment by victorcfk** [comment]
Yes, I'm running it on Vulkan

**Comment by keijiro** [comment]
Okay. Then I think there is almost nothing to do it. As far as I tried, Barracuda on mobile runs slower than TensorFlow Lite in some cases. I wonder if you should try other TFLite on Unity solutions instead.

**Comment by victorcfk** [comment]
Got it. Thanks for the redirect. Looking at asus4 tf-lite right now. Thank you for the redirect! :)
