### ISSUE TITLE
Question: How to save a dataset?

### ISSUE THREAD

**Issue by Takefumi777** [keijiro/FaceMeshBarracuda#18]
Hi  @keijiro, thank you for the great project.
I am currently using this project to do research on mouth movements.
My question is: I would like to save my mouth movements as a dataset using this project.
I would like to know if it is possible to do that.

I am waiting for your reply. Thank you in advance.

**Comment by keijiro** [comment]
You can read the raw mesh data using [GetData](https://docs.unity3d.com/ScriptReference/ComputeBuffer.GetData.html).

https://github.com/keijiro/FaceMeshBarracuda/blob/main/Assets/FaceMesh/Script/FacePipeline_Public.cs#L15
