### ISSUE TITLE
Load Custom Face Mesh

### ISSUE THREAD

**Issue by Blargstomp404** [keijiro/FaceMeshBarracuda#2]
We have a custom mesh for our project, is there a way to load that custom face mesh to use? Its currently setup with a neck and head bone, and it has blendshapes for face movements.

**Comment by keijiro** [comment]
FaceMeshBarracuda is just an example that runs the MediaPipe face mesh pipeline on Barracuda. You can use it to drive your own mesh. You have to write conversion code yourself, though.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further issues.
