### ISSUE TITLE
Facemesh visualization broken - Not rendered correctly 

### ISSUE THREAD

**Issue by cri30** [keijiro/FaceMeshBarracuda#20]
Hi,

very nice project, but I have some issues running it (with camera and based on the provided png files). 
As you see from the pictures, the rendering of the mesh doesn't work as expected. 
I have only downloaded the project and opened it in Unity, running the Visualizer scene.  

OS: Windows 10 
Unity version: 2021.1.3
Intel Iris Xe Grafik

![MeshBroken](https://user-images.githubusercontent.com/53139194/198294265-23a0edcd-c039-4a70-aefd-e9a040e72ee0.png)

**Comment by keijiro** [comment]
Could you try simpler projects like this?

https://github.com/keijiro/FaceLandmarkBarracuda

**Comment by cri30** [comment]
I can see something. But the face mesh position or the movements are not reflecting my real behaviour.

**Comment by keijiro** [comment]
Could you attach a screenshot?

**Comment by cri30** [comment]
![image](https://user-images.githubusercontent.com/53139194/198579558-14138829-ba74-4548-9336-022aa8b1e13b.png)

**Comment by keijiro** [comment]
Thanks. At least, it doesn't seem broken.

(It doesn't reflect you movement because your face isn't properly cropped. That's not a problem at this point.)

So, it breaks up the things only on the complex pipeline.

At the moment, I have no idea. Have you updated your graphics driver?

**Comment by cri30** [comment]
Exactly, it's not broken but it's also not aligned with my face.

Drivers are updated

**Comment by keijiro** [comment]
I realized the the screenshot you attached came from FaceLandmarkBarracuda -- that's not this repository.

I close this issue as irrelevant. Please create a new issue in the correct repository (FaceLandmarkBarracuda) if you still has the same issue on your side.
