### ISSUE TITLE
Problem importing to another project

### ISSUE THREAD

**Issue by Boulaouaney** [keijiro/FaceMeshBarracuda#21]
I am trying to export the project with the dependencies but it doesn't seem to export all the necessary dependcies. 

When I import it into a different project, I get dependencies error. Can you please provide a solution? 
Thank you

**Comment by keijiro** [comment]
You have to import the dependent packages.

https://github.com/keijiro/FaceMeshBarracuda/blob/main/Packages/manifest.json

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
