### ISSUE TITLE
Issue generating visual studio solution

### ISSUE THREAD

**Issue by Boulaouaney** [keijiro/FaceMeshBarracuda#22]
I am tryint to browse the code to understanding more for the purpose of implementing something similar to the mediapipe effect renderer. However, it's a bit challenging browsing it because for some reason, unity is not creating the .sln file. And when I try to open as a C# project, it gives the error below:

I am on windows 11, Unity 2021.1.3f1, Visual Studio 2022

![image](https://user-images.githubusercontent.com/43298428/200716843-3e63e97a-8124-421c-b810-bce5dd1bf648.png)

I have searched for info about this error, and they usually say to try to fix the file locations of the files specified in the error. However, as you can see above, the error message is just blank, no files were specified. Do you have an idea on how to fix this or maybe a workaround?
thanks!

**Comment by keijiro** [comment]
I've never used Visual Studio with Unity (seriously!)

So, unfortunately, I don't have any idea with it. I'd recommend other communities like Forum to solve your problem.
