### ISSUE TITLE
Possible to share fbx/obj model of TemplateMesh.asset file

### ISSUE THREAD

**Issue by BatyrBUT** [keijiro/FaceMeshBarracuda#26]
Hello, wanted to know if its possible to share fbx/obj model of the TemplateMesh.asset file. We need to modify the mesh slightly and cant seems to extract/convert to fbx/obj formats as the TemplateMesh.asset file is packaged.

**Comment by keijiro** [comment]
There is no fbx/obj because it's generated by code: https://github.com/keijiro/FaceLandmarkBarracuda/blob/main/Assets/Editor/TemplateBuilder.cs
