### ISSUE TITLE
What is the last 468 float4 in the RefinedFaceVertexBuffer Data?

### ISSUE THREAD

**Issue by newyellow** [keijiro/FaceMeshBarracuda#27]
Hi keijiro,

Thank you for the amazing tool!
Today I try to grab the faceLandmarks data in the FacePipeline from c# script, and it works well.

And inside the _pipeline.RefinedFaceVertexBuffer, there are total 936 float4,
which the first 468 are faceLandmarks for the faceMesh, and there are another 468 float4 I couldn't figure out what they are.

![face](https://github.com/keijiro/FaceMeshBarracuda/assets/8190143/36efc12e-6ff9-4ad3-82d8-97e272494a6c)

They seems to have a face shape, but only have values when I move. Are they something like motion vectors?

Just curious, and thank you for the time!

**Comment by keijiro** [comment]
They're delta values for the low-pass filter.
https://github.com/keijiro/FaceMeshBarracuda/blob/cf6199d2b07555d9e4554ed4d4b097b25082f314/Assets/FaceMesh/Shader/Postprocess.compute#L108

**Comment by newyellow** [comment]
@keijiro thank you for the quick answer!!

**Comment by remiengel** [comment]
Hi @newyellow !

Today I am trying to do exactly what you mentioned ("grab the faceLandmarks data in the FacePipeline from c# script").
Just started, but I'm struggling a bit.

Would you be ok to share the part of your code that grabs the 468 landmarks ?
It'd be extremely helpful. Thanks.

Edit : just made it !
Here is the added code for whoever might want to achieve the same result.

In `Visualizer.cs`, add a private member for storing the vertices :

`Vector4[] _vertices;`

In the `Start()` method, initialize vertices with the right number of elements (468 for the face landmarks, 936 if you want the added delta values described in the thread)

`_vertices = new Vector4[468];`

In the OnRenderObject() method, add

`_pipeline.RefinedFaceVertexBuffer.GetData(_vertices);`

And now `_vertices` is filled with the vertex data.
