### ISSUE TITLE
Iris direction

### ISSUE THREAD

**Issue by Rujipas-Thongpao** [keijiro/FaceMeshBarracuda#28]
Hi Keijiro,

First of all, thank you for this amazing project! I have been experimenting with this repo, and it works so well. However, I am interested in using this to predict the direction of a player's iris ( left, right, up, down).

I try to get the data from the graphic buffer `_pipeline.RawLeftEyeVertexBuffer`, but i have 0.5 knowledge on compute shader
Could you please provide some guidance or example code on how to achieve this? 

Thank you for your time and assistance!
paopeaw

**Comment by keijiro** [comment]
You can use these extensions.

https://github.com/keijiro/IrisBarracuda/blob/e1372d7285e060a10c233e0e88ca5a97ccaee99c/Packages/jp.keijiro.mediapipe.iris/Runtime/EyeLandmarkDetectorExtensions.cs#L13-L28

**Comment by Rujipas-Thongpao** [comment]
Ok TYSM!!
