### ISSUE TITLE
cumulate openpose et facemesh predictions with barracuda

### ISSUE THREAD

**Issue by ghost** [keijiro/FaceMeshBarracuda#3]
Hi @keijiro ,

Hope you are all well !

I was wondering if it is possible to cumulate facemesh and openpose on a unity chan avatar from a video input.

Like, https://github.com/digital-standard/ThreeDPoseUnityBarracuda, and your repository ?

Thanks for any insights or inputs on that.

Ps. Your repositories are just awesome, thanks for sharing with us.

Cheers,
Luc Michalski

**Comment by keijiro** [comment]
This repository is dedicated to the Face Mesh pipeline. Pose detection is out of the scope.

With regard to pose detection, I have a plan to port the MediaPipe Pose model to Barracuda, but there is no firm schedule about it.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by ghost** [comment]
sorry I did not knew where to post this issue since no repo about posenet/openpose was created.
