### ISSUE TITLE
video frames instead of webcam at input

### ISSUE THREAD

**Issue by syed-naveed-qamar** [keijiro/FaceMeshBarracuda#6]
Hello keijiro,
Hope you are fine, I am new to Unity and c-sharp so can you provide ideas as to how I can input a video clip instead of a webcam input. If you have done any work on it, that can be very helpful as I would have direct ideas of how to integrate it.

**Comment by keijiro** [comment]
You can use the VideoPlayer component instead of the WebcamTexture object.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further bugs/issues with this specific project.
