### ISSUE TITLE
Shader error on Metal

### ISSUE THREAD

**Issue by Ommand** [keijiro/FaceMeshBarracuda#8]
Shader is failing on launch with error (Unity Editor)
```
Metal: Error creating pipeline state (Hidden/MediaPipe/FaceMesh/Preprocess): Link failed: The type of fragment input user(TEXCOORD0) does not match the type of the corresponding vertex shader output
(null)
```

Unity 2020.3.24f1 
Target: iOS

**Comment by keijiro** [comment]
I think you can simply ignore that message.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by Ommand** [comment]
It works like this
![gif](https://user-images.githubusercontent.com/5425054/147541623-023c8295-d52a-4432-a434-37186263c13f.gif)

**Comment by keijiro** [comment]
Please submit a new issue. This doesn't seem a "shader error".

**Comment by Ommand** [comment]
Ok, thanks. It was the only error so I thought it's related.
